In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
df = pd.DataFrame(
        [[60, 1500000, "buen_cliente"],
         [30, 1550000, "mal_cliente"],
         [20, 900000, "buen_cliente"]],
         columns=["edad", "salario", "clase"]
)

In [ ]:
p = [32, 1520000]

In [ ]:
np.linalg.norm(df[["edad", "salario"]] - p, axis=1)

array([ 20000.01959999,  30000.00006667, 620000.00011613])

In [ ]:
model = KNeighborsClassifier(n_neighbors=1)

In [ ]:
model.fit(X=df[["edad", "salario"]], y=df["clase"])

KNeighborsClassifier(n_neighbors=1)

In [ ]:
model.predict([p])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['buen_cliente'], dtype=object)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
scaler.fit(df[["edad", "salario"]])
df_scaled = scaler.transform(df[["edad", "salario"]])

In [ ]:
df_scaled

array([[1.        , 0.92307692],
       [0.25      , 1.        ],
       [0.        , 0.        ]])

In [ ]:
p_scaled = scaler.transform([p])
p_scaled

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.3       , 0.95384615]])

In [ ]:
model = KNeighborsClassifier(n_neighbors=1)
model.fit(X=df_scaled, y=df["clase"] )

KNeighborsClassifier(n_neighbors=1)

In [ ]:
model.predict(p_scaled)

array(['mal_cliente'], dtype=object)

In [ ]:
#1.700.000 19  ???
p_scaled = scaler.transform([[19, 1700000]])
model.predict(p_scaled)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array(['mal_cliente'], dtype=object)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
df = pd.DataFrame(
    [[3,0,110],
     [4,1,200],
     [4,0,300],
     [5,0,50],
     [10,1,100],
     [20,0,20],],columns=["x1","x2","y"]
)

In [ ]:
model = KNeighborsRegressor(n_neighbors=1)

In [ ]:
model.fit(X=df[["x1","x2"]], y=df["y"])

KNeighborsRegressor(n_neighbors=2)

In [ ]:
model.predict([[4.2,1]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([250.])